### PR TITLE
java.nio.file.Path converter

### PR DESCRIPTION
**Pull request by aaron13100**
a java.nio.file.Path converter for enhancement request https://github.com/x-stream/xstream/issues/33

### CODE REVIEW

**Comment by aaron13100** [comment]
I'm unclear on the Travis CI requirements because, for example, com.thoughtworks.acceptance.LambdaTest clearly requires Java 8.

thanks

**Comment by joehni** [comment]
Hi Aaron, thanks for the contribution. You may rewrite the PathConverter using no reflection, it is fine for me, if Travis passes JDK 8+7 builds. I will tweak the Maven build to support the older JDKs (the converter will actually be excluded).

**Comment by aaron13100** [comment]
Great! I've removed the reflection from the converter.

I left it for the call to xstream.alias() though because it creates an alias based on the concrete implementation of java.nio.file.Path (e.g. sun.nio.fs.UnixPath, sun.nio.fs.WindowsFileSystem). I couldn't find a precedent for this in the code. 

I couldn't find a way to re-launch the Travis CI builds.

**Comment by joehni** [comment]
Thanks!

**Pull request closed without merging**
