### PR TITLE
Use ArrayList instead of LinkedList.

### PR DESCRIPTION
**Pull request by madlexa**

### CODE REVIEW

**Comment by joehni** [comment]
Why should we?

**Comment by madlexa** [comment]
Because ArrayList uses less memory and runs faster.

**Comment by danieljohngomez** [comment]
ArrayList costs O(n) for adding elements unlike LinkedList which is O(1) then you added complexity by doing Collections.reverse() which is again linear.

**Comment by madlexa** [comment]
I have removed Collections.reverse()
I do not understand why `ArrayList costs O(n) for adding elements`?
e.g. Joshua Bloch does not like LinkedList and considers it useless.

**Pull request closed without merging**
