### PR TITLE
Provide example that works

### PR DESCRIPTION
**Pull request by biergit**

### CODE REVIEW

**Comment by joehni** [comment]
The only problem I saw, was the wrong closing tag for the _handler_ element.

**Comment by biergit** [comment]
> 
> 
> The only problem I saw, was the wrong closing tag for the _handler_ element.
I did `xstream.alias("contact",` `ContactImpl.class);`
and get
`com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field org.company.model.ContactImpl.dynamic-proxy`

**Comment by biergit** [comment]
Also the documentation says: 

> Use XStream to marshal such an object to XML.

I don't think it is necessary to reproduce the problem.

**Comment by joehni** [comment]
At least you were right, that it did not work that way. I fixed the example now.

**Pull request closed without merging**
